#!/usr/bin/env bash
# Displays "Best school" for other iterations
# "bad luck" for 4th iteration
# "good luck for 8th iteration"

count=0

while [ $count -lt 10 ]
do
   if [ $count -eq 3 ]
   then
	echo "bad luck"
   elif [ $count -eq 7 ]
   then
	echo "good luck"
   else
	echo "Best School"
   fi
   (( count++ ))
done
